### ISSUE TITLE
python test running  error in anaconda environment with windows 10

### ISSUE THREAD

**Issue by hws203** [caiyuanhao1998/SAX-NeRF#22]
Below is my error case log.

I am using windows 10 with anaconda.
All requirement installed well. But there is some error as like below
Please give me any comments.

(sax_nerf) E:\tmp\output\newdata\SAX-NeRF-master>python test.py --method Lineformer --category chest --config config/Lineformer/chest_50.yaml --weights pretrained/chest.tar --output_path output
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
Traceback (most recent call last):
  File "E:\tmp\output\newdata\SAX-NeRF-master\test.py", line 29, in <module>
    from src.encoder import get_encoder
  File "E:\tmp\output\newdata\SAX-NeRF-master\src\encoder\__init__.py", line 1, in <module>
    from .hashencoder import HashEncoder
  File "E:\tmp\output\newdata\SAX-NeRF-master\src\encoder\hashencoder\__init__.py", line 1, in <module>
    from .hashgrid import HashEncoder
  File "E:\tmp\output\newdata\SAX-NeRF-master\src\encoder\hashencoder\hashgrid.py", line 8, in <module>
    from .backend import _backend
  File "E:\tmp\output\newdata\SAX-NeRF-master\src\encoder\hashencoder\backend.py", line 7, in <module>
    _backend = load(name='_hash_encoder',
  File "C:\ProgramData\Anaconda3\envs\sax_nerf\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "C:\ProgramData\Anaconda3\envs\sax_nerf\lib\site-packages\torch\utils\cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\ProgramData\Anaconda3\envs\sax_nerf\lib\site-packages\torch\utils\cpp_extension.py", line 1456, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\ProgramData\Anaconda3\envs\sax_nerf\lib\site-packages\torch\utils\cpp_extension.py", line 1858, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "C:\ProgramData\Anaconda3\envs\sax_nerf\lib\site-packages\torch\utils\cpp_extension.py", line 1626, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by hws203** [comment]
I wonder that windows OS is supported too.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

It seems that you did not install cuda or did not set the env path correctly

Yes, I suggest you switch to ubuntu OS for smoother operations.

If you find our work useful, please help us star this repo, thanks :)

**Comment by hws203** [comment]
@caiyuanhao1998 I found that your default config_parser's gpu_id is 6, that is the key problem at my case, after change this 6 to 0, then this issue solved.
