### ISSUE TITLE
DLL load failed while importing _Ax: 找不到指定的模块。

### ISSUE THREAD

**Issue by NoOne-del-6** [caiyuanhao1998/SAX-NeRF#35]
from _Ax import _Ax_ext

执行gengeateData.py文件时，出现错误，
Traceback (most recent call last):
  File "D:\working\research\SAX-NeRF\dataGenerator\generateData.py", line 3, in <module>
    import tigre
  File "D:\working\research\SAX-NeRF\TIGRE-2.3\Python\tigre\__init__.py", line 4, in <module>
    from .utilities.Ax import Ax
  File "D:\working\research\SAX-NeRF\TIGRE-2.3\Python\tigre\utilities\Ax.py", line 4, in <module>
    from _Ax import _Ax_ext
ImportError: DLL load failed while importing _Ax: 找不到指定的模块。

求助。

**Comment by caiyuanhao1998** [comment]
你好这是因为你没有正确安装 TIGRE toolbox。请按照我们的 readme 的介绍安装一下。另外建议不要使用 windows 系统，用 ubuntu。windows 系统有很多莫名奇怪的 bug
