### ISSUE TITLE
SAX-NeRF testing error

### ISSUE THREAD

**Issue by wjz1316** [caiyuanhao1998/SAX-NeRF#6]
python : 3.9
cuda : 11.3
pytorch : 1.10
torch.cuda.is_available() : true

I an trying to run testing about part of sax-nerf which does not work, could you have a look please? thanks
```No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3'
Traceback (most recent call last):
  File "C:\3dgs\SAX-NeRF\test.py", line 29, in <module>
    from src.encoder import get_encoder
  File "C:\3dgs\SAX-NeRF\src\encoder\__init__.py", line 1, in <module>
    from .hashencoder import HashEncoder
  File "C:\3dgs\SAX-NeRF\src\encoder\hashencoder\__init__.py", line 1, in <module>
    from .hashgrid import HashEncoder
  File "C:\3dgs\SAX-NeRF\src\encoder\hashencoder\hashgrid.py", line 8, in <module>
    from .backend import _backend
  File "C:\3dgs\SAX-NeRF\src\encoder\hashencoder\backend.py", line 6, in <module>
    _backend = load(name='_hash_encoder',
  File "C:\Anaconda\envs\test\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "C:\Anaconda\envs\test\lib\site-packages\torch\utils\cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Anaconda\envs\test\lib\site-packages\torch\utils\cpp_extension.py", line 1456, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Anaconda\envs\test\lib\site-packages\torch\utils\cpp_extension.py", line 1857, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "C:\Anaconda\envs\test\lib\site-packages\torch\utils\cpp_extension.py", line 1626, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range```

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interests.

Using windows system usually leads to many unnecessary problems like this.

I suggest you use Ubuntu system to run our code. Then this bug may be resolved.

If you find our repo useful, please help us star it.

**Comment by wjz1316** [comment]
I try to use Ubuntu20.04  to run it, but it also exist. I completely followed your tutorial to create the environment. Are there any other steps that I may have missed.
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
Traceback (most recent call last):
  File "/workspace/SAX-NeRF/test.py", line 29, in <module>
    from src.encoder import get_encoder
  File "/workspace/SAX-NeRF/src/encoder/__init__.py", line 1, in <module>
    from .hashencoder import HashEncoder
  File "/workspace/SAX-NeRF/src/encoder/hashencoder/__init__.py", line 1, in <module>
    from .hashgrid import HashEncoder
  File "/workspace/SAX-NeRF/src/encoder/hashencoder/hashgrid.py", line 8, in <module>
    from .backend import _backend
  File "/workspace/SAX-NeRF/src/encoder/hashencoder/backend.py", line 6, in <module>
    _backend = load(name='_hash_encoder',
  File "/root/miniconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/root/miniconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1456, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/root/miniconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1858, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/root/miniconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```

**Comment by caiyuanhao1998** [comment]
What commend did you execute in the terminal?

The error message "No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'" indicates that the CUDA runtime is not properly detected or configured. The traceback ends with an IndexError: list index out of range which is related to the CUDA architecture flags being set up improperly or not being available.

Here’s how you can troubleshoot and potentially resolve this issue:

Check CUDA Installation and Environment Variable:

Ensure that CUDA is properly installed at /usr/local/cuda-11.3 or the path specified in your CUDA_HOME environment variable.
Check if the CUDA binaries are correctly linked by running nvcc --version or which nvcc to confirm that nvcc is in your path.
Verify PyTorch and CUDA Compatibility:

Ensure that your PyTorch installation is compatible with CUDA 11.3. You can check PyTorch's CUDA compatibility from the [official PyTorch website](https://pytorch.org/).
Update or reinstall PyTorch if necessary to match your CUDA version.
Check GPU and Driver:

Run nvidia-smi to check if your NVIDIA drivers are up to date and compatible with CUDA 11.3.
Ensure that the GPU is recognized by the system and the drivers are loaded.
CUDA Architecture Flags:

The error arch_list[-1] += '+PTX' suggests that the script tries to append to an empty list. This can happen if the CUDA capability of the GPUs is not correctly detected.
Manually specify the GPU architecture in your setup script if automatic detection fails. For instance, if using an NVIDIA Turing GPU, you can add something like this to your setup script:
python
Copy code
extra_compile_args={'cxx': ['-g'],
                    'nvcc': ['-O2', '-arch=sm_75']}
Check the Python Environment:

Sometimes, the Python environment might not have the correct paths or permissions set up. Make sure that the Python environment has access to CUDA paths.
Reinstall the environment or create a new one if issues persist.
Run a Minimal Example:

Test if CUDA works with a minimal PyTorch script to rule out issues specific to your project setup.

```sh
Copy code
import torch
print(torch.cuda.is_available())
```

If after these steps you still face issues, you may need to provide more details about your system setup, or consider simplifying your CUDA architecture settings in your project configuration.

**Comment by Golden-Pigeon** [comment]
Maybe you could try 
```shell
$ export TORCH_CUDA_ARCH_LIST="X.X+PTX"
```
before you run the training script. where `X.X` is the CUDA Capability of your GPU.
You can use "Samples/1_Utilities/deviceQuery" in [CUDA Samples](https://github.com/NVIDIA/cuda-samples) to get your CUDA Capability. **For example**:
```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce RTX 4070"
  CUDA Driver Version / Runtime Version          12.5 / 11.3
  CUDA Capability Major/Minor version number:    8.9
  Total amount of global memory:                 12282 MBytes (12878086144 bytes)
  (046) Multiprocessors, (128) CUDA Cores/MP:    5888 CUDA Cores
  GPU Max Clock rate:                            2520 MHz (2.52 GHz)
  Memory Clock rate:                             10501 Mhz
  Memory Bus Width:                              192-bit
  L2 Cache Size:                                 37748736 bytes
# The following is omitted...
```
on my PC, the CUDA Capability is 8.9, so I should use
```shell
$ export TORCH_CUDA_ARCH_LIST="8.9+PTX"
```
Hope the above content can help.

**Comment by caiyuanhao1998** [comment]
Thank you for answering the questions :)
